
build_app:
  stage: build
  image: node:6.11.5
  artifacts:
    paths:
      - dist
    expire_in: 1 week
  script:
    - npm install
    - npm run build_prod

pages:
  stage: deploy
  script:
    - mv dist/ public/
  artifacts:
    paths:
      - public
  only:
    - master
